-- MySQL/migrations/001_create_business_profiles.sql
CREATE TABLE IF NOT EXISTS `business_profiles` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` VARCHAR(50) UNIQUE NOT NULL,
    `business_name` VARCHAR(255) NOT NULL,
    `business_type` VARCHAR(100) NOT NULL,
    `description` TEXT,
    `owner_id` INT,
    `owner_name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(50),
    `website` VARCHAR(255),
    `address` TEXT NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `country` VARCHAR(100) NOT NULL DEFAULT 'USA',
    `postal_code` VARCHAR(20),
    `latitude` DECIMAL(10, 8),
    `longitude` DECIMAL(11, 8),
    `business_hours` JSON,
    `logo_url` VARCHAR(500),
    `cover_image_url` VARCHAR(500),
    `accreditation_level` ENUM('none', 'basic', 'premium', 'verified') DEFAULT 'none',
    `accreditation_date` DATETIME,
    `accreditation_expiry` DATETIME,
    `status` ENUM('pending', 'active', 'suspended', 'rejected', 'inactive') DEFAULT 'pending',
    `verification_status` ENUM('unverified', 'pending', 'verified') DEFAULT 'unverified',
    `rating` DECIMAL(3, 2) DEFAULT 0.00,
    `total_reviews` INT DEFAULT 0,
    `total_complaints` INT DEFAULT 0,
    `response_rate` DECIMAL(5, 2) DEFAULT 0.00,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_business_id` (`business_id`),
    INDEX `idx_owner_id` (`owner_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_accreditation` (`accreditation_level`),
    INDEX `idx_location` (`city`, `state`, `country`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
