-- MySQL/migrations/005_create_business_locations_tables.sql
CREATE TABLE IF NOT EXISTS `business_locations` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `location_type` ENUM('headquarters', 'branch', 'franchise', 'partner') NOT NULL,
    `is_primary` BOOLEAN DEFAULT FALSE,
    `address` TEXT NOT NULL,
    `city` VARCHAR(100) NOT NULL,
    `state` VARCHAR(100) NOT NULL,
    `country` VARCHAR(100) NOT NULL DEFAULT 'USA',
    `postal_code` VARCHAR(20),
    `latitude` DECIMAL(10, 8),
    `longitude` DECIMAL(11, 8),
    `phone` VARCHAR(50),
    `email` VARCHAR(255),
    `manager_name` VARCHAR(255),
    `manager_phone` VARCHAR(50),
    `manager_email` VARCHAR(255),
    `status` ENUM('active', 'inactive', 'pending', 'closed') DEFAULT 'active',
    `opening_date` DATE,
    `closing_date` DATE,
    `facilities` JSON,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_business` (`business_id`),
    INDEX `idx_location_type` (`location_type`),
    INDEX `idx_primary` (`is_primary`),
    INDEX `idx_status` (`status`),
    INDEX `idx_city_state` (`city`, `state`),
    INDEX `idx_country` (`country`),
    INDEX `idx_coordinates` (`latitude`, `longitude`),
    FOREIGN KEY (`business_id`) REFERENCES `business_profiles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `business_hours` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `location_id` INT NOT NULL,
    `day_of_week` ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday') NOT NULL,
    `open_time` TIME,
    `close_time` TIME,
    `is_closed` BOOLEAN DEFAULT FALSE,
    `created_at` DATETIME NOT NULL,
    UNIQUE KEY `unique_location_day` (`location_id`, `day_of_week`),
    INDEX `idx_location` (`location_id`),
    INDEX `idx_day` (`day_of_week`),
    FOREIGN KEY (`location_id`) REFERENCES `business_locations`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
