-- MySQL/migrations/007_create_business_subscriptions_tables.sql
CREATE TABLE IF NOT EXISTS `business_subscriptions` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` INT NOT NULL,
    `tier` ENUM('free', 'basic', 'professional', 'enterprise') NOT NULL DEFAULT 'free',
    `status` ENUM('active', 'inactive', 'suspended', 'cancelled', 'expired') DEFAULT 'inactive',
    `start_date` DATETIME NOT NULL,
    `end_date` DATETIME,
    `renewal_date` DATETIME,
    `auto_renew` BOOLEAN DEFAULT TRUE,
    `payment_method` VARCHAR(100),
    `billing_cycle` ENUM('monthly', 'quarterly', 'yearly') DEFAULT 'monthly',
    `monthly_price` DECIMAL(10, 2) DEFAULT 0.00,
    `features` JSON,
    `status_reason` TEXT,
    `cancellation_reason` TEXT,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    UNIQUE KEY `unique_business` (`business_id`),
    INDEX `idx_business` (`business_id`),
    INDEX `idx_tier` (`tier`),
    INDEX `idx_status` (`status`),
    INDEX `idx_end_date` (`end_date`),
    FOREIGN KEY (`business_id`) REFERENCES `business_profiles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `newsletter_templates` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` INT NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    `subject` VARCHAR(255) NOT NULL,
    `content` TEXT NOT NULL,
    `is_active` BOOLEAN DEFAULT TRUE,
    `variables` JSON,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_business` (`business_id`),
    INDEX `idx_active` (`is_active`),
    FOREIGN KEY (`business_id`) REFERENCES `business_profiles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `newsletter_campaigns` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` INT NOT NULL,
    `template_id` INT,
    `name` VARCHAR(255) NOT NULL,
    `subject` VARCHAR(255) NOT NULL,
    `content` TEXT NOT NULL,
    `status` ENUM('draft', 'scheduled', 'sending', 'sent', 'cancelled') DEFAULT 'draft',
    `scheduled_at` DATETIME,
    `sent_at` DATETIME,
    `recipient_count` INT DEFAULT 0,
    `open_count` INT DEFAULT 0,
    `click_count` INT DEFAULT 0,
    `unsubscribe_count` INT DEFAULT 0,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    INDEX `idx_business` (`business_id`),
    INDEX `idx_template` (`template_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_scheduled` (`scheduled_at`),
    INDEX `idx_sent` (`sent_at`),
    FOREIGN KEY (`business_id`) REFERENCES `business_profiles`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`template_id`) REFERENCES `newsletter_templates`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `newsletter_subscribers` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `business_id` INT NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `first_name` VARCHAR(100),
    `last_name` VARCHAR(100),
    `phone` VARCHAR(50),
    `is_active` BOOLEAN DEFAULT TRUE,
    `subscription_token` VARCHAR(64) NOT NULL,
    `unsubscribed_at` DATETIME,
    `source` VARCHAR(100),
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    UNIQUE KEY `unique_business_email` (`business_id`, `email`),
    INDEX `idx_business` (`business_id`),
    INDEX `idx_email` (`email`),
    INDEX `idx_active` (`is_active`),
    INDEX `idx_token` (`subscription_token`),
    FOREIGN KEY (`business_id`) REFERENCES `business_profiles`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `campaign_sends` (
    `id` INT PRIMARY KEY AUTO_INCREMENT,
    `campaign_id` INT NOT NULL,
    `subscriber_id` INT NOT NULL,
    `sent_at` DATETIME,
    `opened_at` DATETIME,
    `clicked_at` DATETIME,
    `unsubscribed_at` DATETIME,
    `bounced_at` DATETIME,
    `ip_address` VARCHAR(45),
    `user_agent` TEXT,
    `metadata` JSON,
    `created_at` DATETIME NOT NULL,
    INDEX `idx_campaign` (`campaign_id`),
    INDEX `idx_subscriber` (`subscriber_id`),
    INDEX `idx_sent` (`sent_at`),
    INDEX `idx_opened` (`opened_at`),
    FOREIGN KEY (`campaign_id`) REFERENCES `newsletter_campaigns`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`subscriber_id`) REFERENCES `newsletter_subscribers`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
